apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis-depl
spec:
  replicas: 1
  selector: # This selector here is how the deployment is going to find the pods that it actually creates
    matchLabels:
      app: expiration-redis
  template:
    metadata:
      labels: # This label is going to be applied to the pod
        app: expiration-redis
    spec:
      containers:
        - name: expiration-redis
          image: redis # This image is coming from a public docker hub which is remotely hosted
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-srv
spec:
  selector: # Remember when we put the selector together inside of a service then it is going to tell which pods it is going to govern access to..
    app: expiration-redis # Find a set of pods (or) any pod with a label of app: expiration-redis
  ports:
    - name: db # The name we put here is just for logging purposes
      protocol: TCP
      port: 6379 # By default Redis listens for incoming traffic on 6379
      targetPort: 6379
